export const FETCH_PEOPLE_REQUEST = 'FETCH_PEOPLE_REQUEST'
export const FETCH_PEOPLE_SUCCESS = 'FETCH_PEOPLE_SUCCESS'
export const FETCH_PEOPLE_FAILURE = 'FETCH_PEOPLE_FAILURE'

export const FETCH_PERSONDETAILS_REQUEST = 'FETCH_PERSONDETAILS_REQUEST'
export const FETCH_PERSONDETAILS_SUCCESS = 'FETCH_PERSONDETAILS_SUCCESS'
export const FETCH_PERSONDETAILS_FAILURE = 'FETCH_PERSONDETAILS_FAILURE'

export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST'
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS'
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE'