//Action type for people
export const FETCH_PEOPLE_REQUEST = "FETCH_PEOPLE_REQUEST";
export const FETCH_PEOPLE_SUCCESS = "FETCH_PEOPLE_SUCCESS";
export const FETCH_PEOPLE_FAILURE = "FETCH_PEOPLE_FAILURE";

//Action type for people details
export const FETCH_PERSONDETAILS_REQUEST = "FETCH_PERSONDETAILS_REQUEST";
export const FETCH_PERSONDETAILS_SUCCESS = "FETCH_PERSONDETAILS_SUCCESS";
export const FETCH_PERSONDETAILS_FAILURE = "FETCH_PERSONDETAILS_FAILURE";

//Action type for movies
export const FETCH_MOVIES_REQUEST = "FETCH_MOVIES_REQUEST";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE";

//Action type for movies details
export const FETCH_MOVIESDETAILS_REQUEST = "FETCH_MOVIESDETAILS_REQUEST";
export const FETCH_MOVIESDETAILS_SUCCESS = "FETCH_MOVIESDETAILS_SUCCESS";
export const FETCH_MOVIESDETAILS_FAILURE = "FETCH_MOVIESDETAILS_FAILURE";

//Action type for planet
export const FETCH_PLANET_REQUEST = "FETCH_PLANET_REQUEST";
export const FETCH_PLANET_SUCCESS = "FETCH_PLANET_SUCCESS";
export const FETCH_PLANET_FAILURE = "FETCH_PLANET_FAILURE";

//Action type for planet details
export const FETCH_PLANETDETAILS_REQUEST = "FETCH_PLANETDETAILS_REQUEST";
export const FETCH_PLANETDETAILS_SUCCESS = "FETCH_PLANETDETAILS_SUCCESS";
export const FETCH_PLANETDETAILS_FAILURE = "FETCH_PLANETDETAILS_FAILURE";
